### ISSUE TITLE
Balatro Crashes when playing the game.

### ISSUE THREAD

**Issue by NamEhcatsoum** [dvrp0/distro#1]
The game works fine up until a deck and stake is selected. Below I will paste the error I recieved (with username censored of course), though obviously no rush in fixing it, I just like the idea of Discord Rich Balatro and this seems to be the only mod to add such a thing.

Oops! The game crashed:
C:\Users\[Username]\AppData\Roaming\Balatro\Mods/d...:166: attempt to index field 'description' (a nil value)

Additional Context:
Balatro Version: 1.0.1g-FULL
Modded Version: 1.0.0~ALPHA-0830b-STEAMODDED
Love2D Version: 11.5.0
Lovely Version: 0.5.0-beta6
Steamodded Mods:
    1: Distro by DVRP [ID: Distro, Version: 1.0.0, Uses Lovely]
Lovely Mods:

Stack Traceback
===============
(3) Lua field 'get_stake_name' at line 166 of chunk '"C:\Users\[Username]\AppData\Roaming\Balatro\Mods/d..."]'
Local variables:
 key = string: "stake_white"
 name = string: "White Stake"
 is_vanilla = string: "stake_white"
 (*temporary) = nil
 (*temporary) = string: "Stake"
 (*temporary) = string: "attempt to index field 'description' (a nil value)"
(4) Lua method 'start_run' at file 'Distro.lua:56' (from mod with id Distro)
Local variables:
 self = table: 0x0bdd0c00  {F_GUIDE:false, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true, HUD_tags:table: 0x0c83ab20 (more...)}
 args = table: 0x0c24ac58  {savetext:table: 0x0c2b9d70}
 back_key = string: "b_checkered"
 back_name = table: 0x0c5215b8  {name:Checkered Deck, text:table: 0x0c521838}
(5) Lua field 'func' at file 'functions/button_callbacks.lua:3021'
(6) Lua method 'handle' at file 'engine/event.lua:99'
Local variables:
 self = table: 0x0c1433a0  {start_timer:true, timer:REAL, func:function: 0x0c0dc960, blockable:true (more...)}
 _results = table: 0x0bfc53c0  {blocking:true, pause_skip:false, time_done:false, completed:false}
(7) Lua method 'update' at file 'engine/event.lua:182'
Local variables:
 self = table: 0x0c3673d8  {queue_last_processed:5.5166666666667, queues:table: 0x0c367400, queue_dt:0.016666666666667 (more...)}
 dt = number: 0.00644592
 forced = nil
 (for generator) = C function: next
 (for state) = table: 0x0c367400  {unlock:table: 0x0c367428, other:table: 0x0c3678a0, tutorial:table: 0x0c367478 (more...)}
 (for control) = number: nan
 k = string: "base"
 v = table: 0x0c367450  {1:table: 0x0c1433a0, 2:table: 0x0c58cbc8, 3:table: 0x0c3972c0, 4:table: 0x0bebde10 (more...)}
 blocked = boolean: false
 i = number: 1
 results = table: 0x0bfc53c0  {blocking:true, pause_skip:false, time_done:false, completed:false}
(8) Lua upvalue 'gameUpdateRef' at file 'game.lua:2490'
Local variables:
 self = table: 0x0bdd0c00  {F_GUIDE:false, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true, HUD_tags:table: 0x0c83ab20 (more...)}
 dt = number: 0
 http_resp = nil
(9) Lua method 'update' at Steamodded file 'core/ui.lua:81' 
Local variables:
 self = table: 0x0bdd0c00  {F_GUIDE:false, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true, HUD_tags:table: 0x0c83ab20 (more...)}
 dt = number: 0.00644592
(10) Lua field 'update' at file 'main.lua:939'
Local variables:
 dt = number: 0.00644592
(11) Lua function '?' at file 'main.lua:880' (best guess)
(12) global C function 'xpcall'
(13) Love2D function at file 'boot.lua:377' (best guess)
Local variables:
 func = Lua function '?' (defined at line 851 of chunk main.lua)
 inerror = boolean: true
 deferErrhand = Lua function '(Love2D Function)' (defined at line 348 of chunk [love "boot.lua"])
 earlyinit = Lua function '(Love2D Function)' (defined at line 355 of chunk [love "boot.lua"])

**Comment by dvrp0** [comment]
Just released [v1.0.0](https://github.com/dvrp0/distro/releases/tag/v1.0.0), this one should be okay. Let me know if you're still getting the error!

**Comment by NamEhcatsoum** [comment]
Don't seem to be getting the error anymore (though I've only just briefly tested), thank you very much!
